### ISSUE TITLE
Conflict with Redshift

### ISSUE THREAD

**Issue by neekt** [WinEunuuchs2Unix/eyesome#2]
First of all, cool app, thanks for developing it!

Perhaps unsurprisingly, there is a conflict with Redshift. At every eyesome refresh interval, the screen reverts to bright white for a few seconds, before switching back again to red. I'm not really looking to replace Redshift for gamma/colour/temperature, and was hoping to simply use eyesome to gradually change the brightness level.

I don't know how difficult it would be to make the two apps compatible, if it's possible at all, but thought I should mention it here.

Another minor mention; under notes here on github you say to use `sudo install.sh rm` to remove the program. That didn't work, but this did: `sudo ./install.sh rm`

**Comment by WinEunuuchs2Unix** [comment]
It was not anticipated someone still needs redshift because eyesome is designed to replace it. It would be better to make eyesome more like redshift to suit your needs rather than breaking eyesome's color temperature (gamma) features. What more does eyesome need to do to suit your needs?

Thank you for pointing out **./install.sh** is needed instead of **install.sh**. On my system the install.sh file was in the path. If a given command is in the current directory (and not in path) one always needs to prepend **./** to the command.

**Comment by WinEunuuchs2Unix** [comment]
I wouldn't know where to begin fixing Redshift or enhancing it with gradual brightness changes. I believe eyesome is better than Redshift though and well worth considering. I've updated the README from `install.sh` to `./install.sh`. Thank you for pointing out that typo.

**Comment by ieremies** [comment]
Hey, just installed the app (love the idea, btw) and I really wanted the option to not change the gamma. Like an on/off button to the gamma feature. I also think this would solve the issue of incompatibility.
