### ISSUE TITLE
When I use ru_UA locale for time/date it causes an error

### ISSUE THREAD

**Issue by SteMak** [WinEunuuchs2Unix/eyesome#6]
In output I see
`date: invalid date ‘Пт 29 янв 2021 09:19:07 EET’`
Then program restarts and I see the same row again
`date: invalid date ‘Пт 29 янв 2021 09:19:09 EET’`

**Comment by WinEunuuchs2Unix** [comment]
My apologies for delay in responding. Please see comment I just posted on same issue for German locale.

**Comment by WinEunuuchs2Unix** [comment]
This problem was corrected for German language and same solution applies to Russian language. As per comment just posted on German language issue:

Bug with Linux date handling in German locale has been corrected. Additionally German language doesn't have AM/PM indicator so display times with 24 hour clock. 

![eyesome german bug fix](https://user-images.githubusercontent.com/33849503/117576577-ba7f6100-b0a3-11eb-9434-9dd2b2b2e073.png)
